# Generated by Django 6.0.5 on 2026-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Qo'shiq nomi")),
                ('artist', models.CharField(max_length=255, verbose_name='Ijrochi')),
                ('icon', models.CharField(default='🎵', max_length=10, verbose_name='Emodji/Ikonka')),
                ('audio_file', models.FileField(upload_to='tracks/', verbose_name='MP3 Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
