# Generated by Django 6.0.5 on 2026-06-17 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_track_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Artist ismi')),
                ('image', models.ImageField(upload_to='artists/', verbose_name="Artist rasmi (Dumaloq bo'ladi)")),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Ijrochi (Matn shaklida)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='track_covers/', verbose_name="Qo'shiq rasmi"),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Albom nomi')),
                ('cover', models.ImageField(upload_to='albums/', verbose_name='Albom muqovasi (Rasm)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan yili')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='apps.artist', verbose_name='Albom muallifi')),
            ],
        ),
    ]
